package dev.gregyyy.dbtimetables.model

import com.fasterxml.jackson.annotation.JsonAlias
import com.fasterxml.jackson.annotation.JsonIncludeProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonRootName

@JsonRootName("timetable")
data class IrisTimetable(
    @JsonProperty("station")
    val station: String,
    @JsonProperty("s")
    val journeys: List<IrisJourney>
)

data class IrisJourney(
    @JsonProperty("tl")
    val trainLine: IrisTrainLine?,
    @JsonProperty("ar")
    val arrival: IrisPoint?,
    @JsonProperty("dp")
    val departure: IrisPoint?,
    @JsonProperty("id")
    val id: String?,
    @JsonProperty("m")
    val messages: List<IrisMessage>?
)

data class IrisTrainLine(
    @JsonProperty("f")
    val distanceClass: String?,
    @JsonProperty("t")
    val tripType: String,
    @JsonProperty("o")
    val owner: String,
    @JsonProperty("c")
    val trainClass: String,
    @JsonProperty("n")
    val number: String
)

data class IrisPoint(
    @JsonProperty("pt")
    val dateTime: String?,
    @JsonProperty("pp")
    val platform: String?,
    @JsonProperty("l")
    val line: String?,
    @JsonProperty("ppth")
    val path: String?,
    @JsonProperty("pde")
    val displayedEndStation: String?,
    @JsonProperty("m")
    val messages: List<IrisMessage>?,
    @JsonProperty("ct")
    val changedTime: String?,
)

data class IrisMessage(
    @JsonProperty("id")
    val id: String,
    @JsonProperty("t")
    val type: IRISMessageType,
    @JsonProperty("c")
    val code: String?,
    @JsonProperty("ts")
    val timestamp: String,
    @JsonProperty("from")
    val from: String?,
    @JsonProperty("to")
    val to: String?,
    @JsonProperty("cat")
    val category: MessageCategory?,
    @JsonProperty("pr")
    val priority: String?,
)

enum class IRISMessageType {
    h, // generated by Hafas Information Manager (HIM)
    q, // message about quality change
    f, // free text message
    d, // cause of delay
    i, // generated by IBIS-AP
    u, // generated by IBIS-AP but not assigned to a train
    r, // major disruption
    c  // connection
}

enum class MessageCategory {
    @JsonAlias("Bauarbeiten. (Quelle: zuginfo.nrw)")
    Bauarbeiten,
    @JsonAlias("Information. (Quelle: zuginfo.nrw)")
    Information,
    @JsonAlias("Störung. (Quelle: zuginfo.nrw)")
    Störung,
    @JsonAlias("Großstörung. (Quelle: zuginfo.nrw)")
    Großstörung
}
